version: '3.8'

services:
  producer:
    build:
      context: .
    container_name: fastapi_producer
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      RABBITMQ_HOST: "rabbitmq" 
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management 
    container_name: rabbitmq_broker
    ports:
      - "5672:5672" 
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    restart: always

  consumer:
    build:
      context: .
    container_name: message_consumer
    volumes:
      - .:/app
    environment:
      RABBITMQ_HOST: "rabbitmq"
    depends_on:
      - rabbitmq
    command: python consumer/pika_consumer.py
    restart: always

volumes:
  rabbitmq_data: